#dev:
  base_path_users_service: https://api-test.store.bbc.com/v2/users
  test_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d
  crm_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d
  drupal_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d

test:
  test_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d
  crm_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d
  drupal_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d

pre-prod:
  test_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d
  crm_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d
  drupal_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d

perf:
  test_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d
  crm_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d
  drupal_apikey: eqeNTWaAPIOBpY1FVL91CWUzlQuaX18d

